version: '3.8'

services:
  backend:
    build: ./backend
    container_name: fullstack-backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=${MONGODB_URI}
      - PORT=5000
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: fullstack-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped